### ISSUE TITLE
Magpleasure_Info_Model_Feed->retrieveFeed(): «Decoding failed: Syntax error in lib/Zend/Json.php:97»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [repairzoom/m1#1]
```
2019-11-26T12:05:17+00:00 ERR (3): 
Zend_Json_Exception: Decoding failed: Syntax error in lib/Zend/Json.php:97
Stack trace:
#0 app/code/local/Magpleasure/Info/Model/Feed.php(123): Zend_Json::decode('\<html>\r\n\<head>\<...')
#1 app/code/local/Magpleasure/Info/Model/Observer.php(56): Magpleasure_Info_Model_Feed->retrieveFeed()
#2 app/code/core/Mage/Core/Model/App.php(1358): Magpleasure_Info_Model_Observer->predispatchPage(Object(Varien_Event_Observer))
#3 app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Magpleasure_Info_Model_Observer), 'predispatchPage', Object(Varien_Event_Observer))
#4 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#5 app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#6 app/code/core/Mage/Adminhtml/Controller/Action.php(167): Mage_Core_Controller_Varien_Action->preDispatch()
#7 app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
#8 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('noroute')
#9 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#11 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#12 index.php(92): Mage::run('', 'store')
#13 {main}
```

**Comment by dmitrii-fediuk** [comment]
```
rm -rf app/code/local/Magpleasure/Info
rm -f app/etc/modules/Magpleasure_Info.xml
```
